[env:NUCLEO_L152RE_release]
platform = ststm32
board = nucleo_l152re
framework = mbed
upload_port = L:\
monitor_port = COM3
upload_protocol = mbed
monitor_speed = 9600

[env:BBS_NUCLEO_L152RE_release]
platform = ststm32
board = nucleo_l152re
framework = mbed
upload_protocol = stlink
debug_tool = stlink
upload_port = 0671FF555651836687023907
monitor_port = COM3
monitor_speed = 9600
